### ISSUE TITLE
Startup problems 1 (plus fix)

### ISSUE THREAD

**Issue by Stefdv** [apguerard/HandleView-DevPreview#1]
Alain, in Mod-xhvStartupApp  you check for a Boolean but the values are Strings! 
This generates the error 13 type mismatch on startup. 
If Configuration("App.UseBackEndPattern") And Configuration("App.KeepBackEndOpen") Then
        OpenAllDatabases True
    End If`

**Temporary fix but i suggest to change the type to boolean in xhvAppConfig**

` If Configuration("App.UseBackEndPattern") = "True" And Configuration("App.KeepBackEndOpen") = "True" Then
        OpenAllDatabases True
    End If`

**Comment by apguerard** [comment]
Hey Stef, thanks for your help :)
My system do an implicit conversion on those value . so I didn't see that coming. 
We cannot change the type in the  table, because all config use the same field and most are Strings.
I'll check for a fix directly when reading the config in the xhvConfigurator class to cast the specific type when adding to the configs dictionary.
Thanks!

**Comment by apguerard** [comment]
I tried something, when you have a second can you check if it works,
Thanks

**Comment by Stefdv** [comment]
Yup, it's fixed 👍 
I close this issue then
